
"""
Dummy ssl module to allow successfull import of pg8000
"""

SSLError = None
CERT_NONE = None
CERT_OPTIONAL = None
CERT_REQUIRED = None
PROTOCOL_SSLv2 = None
PROTOCOL_SSLv3 = None
PROTOCOL_SSLv23 = None
PROTOCOL_TLSv1 = None
RAND_status = None
RAND_egd = None
RAND_add = None
SSL_ERROR_ZERO_RETURN = None
SSL_ERROR_WANT_READ = None
SSL_ERROR_WANT_WRITE = None
SSL_ERROR_WANT_X509_LOOKUP = None
SSL_ERROR_SYSCALL = None
SSL_ERROR_SSL = None
SSL_ERROR_WANT_CONNECT = None
SSL_ERROR_EOF = None
SSL_ERROR_INVALID_ERROR_CODE = None